name: ボット100体チャレンジの記録を追加する

on:
  workflow_dispatch:
    inputs:
      date:
        type: string
        description: 日付をYYYY-MM-DDで入力
      best_time:
        type: number
        description: その日のベストスコア（秒）を入力

jobs:
  add_record:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      CHALLENGE_DATE: ${{ github.event.inputs.date }}
      BEST_TIME: ${{ github.event.inputs.best_time }}
      BRANCH_NAME: add-record-${{ github.event.inputs.date }}
    steps:
      - uses: actions/checkout@v2

      - name: 記録をJSONファイルに追記
        run: |
          CURRENT=$(cat ./100-bots-challenge.json)
          echo $CURRENT | jq ".records=.records + [{\"date\":\"$CHALLENGE_DATE\", \"best_time\": $BEST_TIME }]" > ./100-bots-challenge.json

      - name: 更新したファイルをコミット
        run: |
          git config --local user.email "${{ vars.commit_email }}"
          git config --local user.name "${{ vars.commit_user_name }}"
          git switch -c ${BRANCH_NAME}
          git add ./100-bots-challenge.json
          git commit -m "Add record of ${{ env.CHALLENGE_DATE }}"
          git push -u origin ${BRANCH_NAME}

      - name: プルリクエストを作成
        run: |
          gh pr create \
            --base main \
            --head ${BRANCH_NAME} \
            --title "Add record of ${{ env.CHALLENGE_DATE }}" \
            --body "Add record of ${CHALLENGE_DATE}
          
            - \`date\`: \`${CHALLENGE_DATE}\`
            - \`best_time\`: \`${BEST_TIME}\`
            "
        env:
          GH_TOKEN: ${{ secrets.token_for_pr }}
